### ISSUE TITLE
挺有意思的，上个截图呀

### ISSUE THREAD

**Issue by SergeyChang** [culturer/yoo_home_Android#29]

**Comment by SergeyChang** [comment]
哈 ，咱加过好友，我 qq叫“我是吉他手”。做的的确挺好的，后台服务我想在你的构建下重构一版，用 gin 或者 echo 框架

**Comment by culturer** [comment]
可以呀，我后台做到挺简陋的，当初后台用beego一方面是beego上手快可以快速培养人来帮忙开发，开发速度快。另一方面是go支持高并发方便以后横向扩展。我一开始想着后期后台需要重构，部分业务会拆分出来成微服务，至于用什么技术无所谓哈，你可以把我的后台拆分一个模块出来用gin或者echo重写。
